version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: exartt
      POSTGRES_PASSWORD: L312f1w3
      POSTGRES_DB: exartt
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c max_connections=500 -c shared_buffers=512MB -c effective_cache_size=1GB -c maintenance_work_mem=256MB -c checkpoint_completion_target=0.7 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=4 -c effective_io_concurrency=2 -c work_mem=64MB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=4 -c max_parallel_workers_per_gather=2 -c max_parallel_workers=4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exartt"]
      interval: 10s
      timeout: 5s
      retries: 5
  flyway:
    build:
      context: .
      dockerfile: dockerfile-flyway
    entrypoint: /bin/sh
    command: -c "while ! pg_isready -h db -U exartt; do sleep 2; done; flyway -url=jdbc:postgresql://db:5432/exartt -user=exartt -password=L312f1w3 migrate"
    volumes:
    - ./src/main/resources/db/migrations:/flyway/sql
    - ./flyway:/flyway/sql
    depends_on:
      - db
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
